version: '3.8'

services:
  redis:
    image: redis
    container_name: redis
    volumes:
      - redis-data:/data

  valuator-1:
    image: valuator
    build:
      context: .
      dockerfile: Valuator/Dockerfile
    depends_on:
      - redis
    volumes:
      - ./keys:/keys
    ports:
      - "5001:8080"

  valuator-2:
    image: valuator
    build:
      context: .
      dockerfile: Valuator/Dockerfile
    depends_on:
      - redis
    volumes:
      - ./keys:/keys
    ports:
      - "5002:8080"

  valuator-3:
    image: valuator
    build:
      context: .
      dockerfile: Valuator/Dockerfile
    depends_on:
      - redis
    volumes:
      - ./keys:/keys
    ports:
      - "5003:8080"

  valuator-4:
    image: valuator
    build:
      context: .
      dockerfile: Valuator/Dockerfile
    depends_on:
      - redis
    volumes:
      - ./keys:/keys
    ports:
      - "5004:8080"

  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:8080"
      - "8081:8081"
      - "8082:8082"
    depends_on:
      - valuator-1
      - valuator-2
      - valuator-3
      - valuator-4

volumes:
  redis-data:
