services:
  valuator:
    image: valuator
    deploy:
      replicas: 2
    build:
      context: .
      dockerfile: Valuator/Dockerfile
    depends_on:
      redis-main:
        condition: service_healthy
      redis-ru:
        condition: service_healthy
      redis-eu:
        condition: service_healthy
      redis-asia:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      centrifugo:
        condition: service_started
    environment:
      - DB_MAIN=redis-main:6379
      - DB_RU=redis-ru:6379
      - DB_EU=redis-eu:6379
      - DB_ASIA=redis-asia:6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}

  rankcalculator:
    image: rankcalculator
    deploy:
      replicas: 2
    build:
      context: .
      dockerfile: RankCalculator/Dockerfile
    depends_on:
      redis-main:
        condition: service_healthy
      redis-ru:
        condition: service_healthy
      redis-eu:
        condition: service_healthy
      redis-asia:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      centrifugo:
        condition: service_started
    environment:
      - DB_MAIN=redis-main:6379
      - DB_RU=redis-ru:6379
      - DB_EU=redis-eu:6379
      - DB_ASIA=redis-asia:6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
  
  eventslogger:
    image: eventslogger
    deploy:
      replicas: 2
    build:
      context: .
      dockerfile: EventsLogger/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
  redis-main:
    image: redis
    volumes:
      - redis-main-data:/data
    command: redis-server --requirepass ${REDIS_PASSWORD}
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "127.0.0.1:6379:6379"
  
  redis-ru:
    image: redis
    volumes:
      - redis-ru-data:/data
    command: redis-server --requirepass ${REDIS_PASSWORD}
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "127.0.0.1:6380:6379"
  
  redis-eu:
    image: redis
    volumes:
      - redis-eu-data:/data
    command: redis-server --requirepass ${REDIS_PASSWORD}
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "127.0.0.1:6381:6379"
  
  redis-asia:
    image: redis
    volumes:
      - redis-asia-data:/data
    command: redis-server --requirepass ${REDIS_PASSWORD}
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "127.0.0.1:6382:6379"
  
  rabbitmq:
    image: rabbitmq:management
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    ports:
      - "127.0.0.1:15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 10s
      timeout: 5s
      retries: 5
  
  nginx:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - valuator
      - rankcalculator
  
  centrifugo:
    image: centrifugo/centrifugo
    volumes:
      - ./centrifugo/config.json:/centrifugo/config.json
    command: centrifugo -c config.json
    ports:
      - "127.0.0.1:8000:8000"

volumes:
  redis-main-data:
  redis-ru-data:
  redis-eu-data:
  redis-asia-data:
  rabbitmq-data: