# This is a generated file. Not intended for manual editing.
services:
  rankcalculator:
    build:
      context: "C:\\Users\\roman\\RiderProjects\\lab-3"
      dockerfile: "RankCalculator/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/RankCalculator.dll"
    environment:
      DOTNET_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "rankcalculator:dev"
    ports: []
    volumes:
    - "C:\\Users\\roman\\RiderProjects\\lab-3\\RankCalculator:/app:rw"
    - "C:\\Users\\roman\\RiderProjects\\lab-3:/src:rw"
    - "C:\\Users\\roman\\.nuget\\packages:/home/app/.nuget/packages"
    working_dir: "/app"
  valuator:
    build:
      context: "C:\\Users\\roman\\RiderProjects\\lab-3"
      dockerfile: "Valuator/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/Valuator.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_STATICWEBASSETS: "/app/bin/Debug/net8.0/Valuator.staticwebassets.runtime.CT.json"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "valuator:dev"
    ports: []
    volumes:
    - "C:\\Users\\roman\\RiderProjects\\lab-3\\Valuator:/app:rw"
    - "C:\\Users\\roman\\RiderProjects\\lab-3:/src:rw"
    - "C:\\Users\\roman\\.nuget\\packages:/home/app/.nuget/packages"
    working_dir: "/app"
